// Country dial (calling) codes for the phone-number country picker. Separate from CURRENCY_PRESETS —
// that list is per-currency (one "European Union" entry, no dial codes), which isn't a clean phone
// dataset. `country` is the ISO 3166-1 alpha-2 code (reused for the flag emoji via currencyFlag).
export type DialCountry = { country: string; name: string; dial: string };

export const COUNTRY_DIAL_CODES: DialCountry[] = [
  { country: "LK", name: "Sri Lanka", dial: "+94" },
  { country: "US", name: "United States", dial: "+1" },
  { country: "CA", name: "Canada", dial: "+1" },
  { country: "GB", name: "United Kingdom", dial: "+44" },
  { country: "IN", name: "India", dial: "+91" },
  { country: "AE", name: "United Arab Emirates", dial: "+971" },
  { country: "JP", name: "Japan", dial: "+81" },
  { country: "AU", name: "Australia", dial: "+61" },
  { country: "CN", name: "China", dial: "+86" },
  { country: "CH", name: "Switzerland", dial: "+41" },
  { country: "HK", name: "Hong Kong", dial: "+852" },
  { country: "SG", name: "Singapore", dial: "+65" },
  { country: "NZ", name: "New Zealand", dial: "+64" },
  { country: "SE", name: "Sweden", dial: "+46" },
  { country: "NO", name: "Norway", dial: "+47" },
  { country: "DK", name: "Denmark", dial: "+45" },
  { country: "DE", name: "Germany", dial: "+49" },
  { country: "FR", name: "France", dial: "+33" },
  { country: "IT", name: "Italy", dial: "+39" },
  { country: "ES", name: "Spain", dial: "+34" },
  { country: "NL", name: "Netherlands", dial: "+31" },
  { country: "BE", name: "Belgium", dial: "+32" },
  { country: "IE", name: "Ireland", dial: "+353" },
  { country: "PT", name: "Portugal", dial: "+351" },
  { country: "AT", name: "Austria", dial: "+43" },
  { country: "GR", name: "Greece", dial: "+30" },
  { country: "FI", name: "Finland", dial: "+358" },
  { country: "IS", name: "Iceland", dial: "+354" },
  { country: "PL", name: "Poland", dial: "+48" },
  { country: "CZ", name: "Czechia", dial: "+420" },
  { country: "HU", name: "Hungary", dial: "+36" },
  { country: "RO", name: "Romania", dial: "+40" },
  { country: "BG", name: "Bulgaria", dial: "+359" },
  { country: "UA", name: "Ukraine", dial: "+380" },
  { country: "RU", name: "Russia", dial: "+7" },
  { country: "TR", name: "Turkey", dial: "+90" },
  { country: "ZA", name: "South Africa", dial: "+27" },
  { country: "BR", name: "Brazil", dial: "+55" },
  { country: "MX", name: "Mexico", dial: "+52" },
  { country: "AR", name: "Argentina", dial: "+54" },
  { country: "CL", name: "Chile", dial: "+56" },
  { country: "CO", name: "Colombia", dial: "+57" },
  { country: "PE", name: "Peru", dial: "+51" },
  { country: "KR", name: "South Korea", dial: "+82" },
  { country: "TW", name: "Taiwan", dial: "+886" },
  { country: "ID", name: "Indonesia", dial: "+62" },
  { country: "MY", name: "Malaysia", dial: "+60" },
  { country: "TH", name: "Thailand", dial: "+66" },
  { country: "PH", name: "Philippines", dial: "+63" },
  { country: "VN", name: "Vietnam", dial: "+84" },
  { country: "PK", name: "Pakistan", dial: "+92" },
  { country: "BD", name: "Bangladesh", dial: "+880" },
  { country: "NP", name: "Nepal", dial: "+977" },
  { country: "MV", name: "Maldives", dial: "+960" },
  { country: "SA", name: "Saudi Arabia", dial: "+966" },
  { country: "QA", name: "Qatar", dial: "+974" },
  { country: "KW", name: "Kuwait", dial: "+965" },
  { country: "BH", name: "Bahrain", dial: "+973" },
  { country: "OM", name: "Oman", dial: "+968" },
  { country: "JO", name: "Jordan", dial: "+962" },
  { country: "LB", name: "Lebanon", dial: "+961" },
  { country: "IQ", name: "Iraq", dial: "+964" },
  { country: "IL", name: "Israel", dial: "+972" },
  { country: "EG", name: "Egypt", dial: "+20" },
  { country: "MA", name: "Morocco", dial: "+212" },
  { country: "NG", name: "Nigeria", dial: "+234" },
  { country: "KE", name: "Kenya", dial: "+254" },
  { country: "GH", name: "Ghana", dial: "+233" },
];
